### ISSUE TITLE
Empty file being generated

### ISSUE THREAD

**Issue by avais88786** [jcundill/cypress-cucumber-preprocessor#8]
Following minimal configurations, I am getting am empty file, incorrect name with no extension.
Configurations I am using:
Package.json:
![image](https://user-images.githubusercontent.com/9274605/60617420-9aa5f480-9dcb-11e9-8849-ef9830441ee7.png)
Folder structure and generated file:
![image](https://user-images.githubusercontent.com/9274605/60617580-f1133300-9dcb-11e9-83d0-aef3d47018e2.png)
I am running command : "cypress run --spec cypress/integration/policysearch.feature"
The generated file is coming as blank with 0 bytes and file name is sort of incorrect, Its always  **cucumber-C** (with no extension)
Any help much appreciated.

p.s. contents of feature file (only 1 scenario)
![image](https://user-images.githubusercontent.com/9274605/60618035-0046b080-9dcd-11e9-8fdf-927c8cd46e00.png)

**Comment by jcundill** [comment]
Hi

I set up a simple project to try and reproduce your empty file problem

git clone https://github.com/jcundill/cuke_test.git

consists of minimal package.json and a very simple cypress feature file.
cucumber json output file formatting is added to the package.json - should dump files in cypress/my-cucumber-files

could you try cloning this example, and running 
npm install
npx cypress run --spec cypress/integration/BackgroundSection.feature
ls -al cypress/my-cucumber-files/

Does this example project still give you the empty file issue your are seeing on your project?
See README.md for the results I see when running this locally

Thanks for reporting this problem

**Comment by avais88786** [comment]
Hi,
Still blank file : 
![image](https://user-images.githubusercontent.com/9274605/60626597-2ecf8600-9de3-11e9-8917-267533ae46dc.png)
I am on Windows 10.

**Comment by jcundill** [comment]
Thanks - it's probably an issue running on windows then. We just use macs and linux boxes. I'll try it on a windows box tomorrow - hopefully that will reproduce the issue. If I can reproduce your problem it shouldn't be too hard to fix

**Comment by avais88786** [comment]
Found the problem I think:

Line 59:
![image](https://user-images.githubusercontent.com/9274605/60628338-f59a1480-9de8-11e9-9968-6814229ecf6c.png)
This is my uri in json : 
`"uri":"C:Commercial Quote Hubcqh-insurer-portal\testsOpenGI.MobiusGatewayPresscypressintegrationpolicysearch.feature"`
I will do some digging as to where this is coming from, let me know if you find something or guide me to the right place.
Thanks

**Comment by jcundill** [comment]
Was a windows issue - I wasn't parsing the filename out of a filepath to the feature file correctly.
now use path.basename in loader.js to get the name from the path
